version: '3'
services:
  server1:
    image: ghcr.io/hounsvad/softwarearchitechture-sdu/performance-sink:latest
    container_name: server1
    restart: unless-stopped
    ports:
      - 8081:80
  server2:
    image: ghcr.io/hounsvad/softwarearchitechture-sdu/performance-sink:latest
    container_name: server2
    restart: unless-stopped
    ports:
      - 8082:80
  loadbalancer:
    image: nginx:latest
    container_name: loadbalancer
    restart: unless-stopped
    ports:
      - 8080:80
      - 8085:8085
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server1
      - server2
    
